export function diaSemanaF(dia){
    switch(dia){
        case(0):
            console.log('Domingo')
            break;
        case(1):
            console.log('Segunda')
            break;
        case(2):
        console.log('Terça')
            break;
        case(3):
        console.log('Quarta')
            break;
        case(4):
        console.log('Quinta')
            break;
        case(5):
        console.log('Sexta')
            break;
        case(6):
        console.log('Sábado')
            break;
        default:
            console.log('Dia da semana inválido')
            break;
    }
}

export function meses(mes){
    switch(mes){
        case(1):
            console.log('Janeiro')
            break;
        case(2):
            console.log('Fevereiro')
            break;
        case(3):
            console.log('Março')
            break;
        case(4):
            console.log('Abril')
            break;
        case(5):
            console.log('Maio')
            break;
        case(6):
            console.log('Junho')
            break;
        case(7):
            console.log('Julho')
            break;
        case(8):
            console.log('Agosto')
            break;
        case(9):
            console.log('Setembro')
            break;
        case(10):
            console.log('Outubro')
            break;
        case(11):
            console.log('Novembro')
            break;
        case(12):
            console.log('Dezembro')
            break;
        default:
            console.log('Mês inválido')
            break;
    }
}